# Generated by Django 4.1.6 on 2023-03-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=25)),
                ('mrp', models.CharField(max_length=25)),
                ('rating', models.CharField(max_length=25)),
                ('image_url', models.CharField(max_length=250)),
            ],
        ),
    ]
